### ISSUE TITLE
Local setup fail

### ISSUE THREAD

**Issue by DrSensor** [NativeScript/docs-v7#1831]
### Please, tell us what's the problem?
[ ] A typo
[ ] Wrong documentation
[ ] Improvement of existing article
[ ] Missing documentation
[ ] New article needed

### Please, tell us more details
Error when doing full [local setup](https://github.com/NativeScript/docs#local-setup) (include optional repos)
```console
$ docker run -t -i -v (pwd):/root -p 9192:9192 -t ns-docs:1.0
.
.
Extracting snippets from: tns-core-modules
fs.js:115
throw err;
^

Error: ENOENT: no such file or directory, lstat 'tns-core-modules'
at Object.lstatSync (fs.js:841:3)
at SnippetExtractor.SnippetInjector.process (/www/NativeScript/node_modules/markdown-snippet-injector/snippet-injector.js:108:30)
at Object.<anonymous> (/www/NativeScript/node_modules/markdown-snippet-injector/extract.js:16:18)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
at startup (internal/bootstrap/node.js:282:19)
```

**Comment by NickIliev** [comment]
Not reproducible on our side - the local setup is working as expected with the optional repositories. Still, you could skip them if you want to make changes that are not reflecting the API references or the additional UI snippets.
