### ISSUE TITLE
Exception when running TypeScript + Angular example at Chapter 1

### ISSUE THREAD

**Issue by realtebo** [NativeScript/docs-v7#531]
I just checkedout 

```
git checkout angular-start
Branch angular-start set up to track remote branch angular-start from origin.
Switched to a new branch 'angular-start'
```

Added Android platform

```
tns platform add android
Copying template files...
Project successfully created.
```

I'm using Genymotion; so I started an emulated Android Device.

Then tried to run

```
C:\Users\mirko\Downloads\groceries>tns run android
Error: Command failed: C:\Users\mirko\AppData\Local\Android\android-sdk\platform-tools\adb devices
error: could not install *smartsocket* listener: cannot bind to 127.0.0.1:5037: Di norma è consentito un solo utilizzo di ogni indirizzo di socket (protocollo/indirizzo di rete/porta). (10048)
could not read ok from ADB Server
* failed to start daemon *
error: cannot connect to daemon
: Command failed: C:\Users\mirko\AppData\Local\Android\android-sdk\platform-tools\adb devices
    at FiberFuture.Future.wait (C:\Users\mirko\AppData\Roaming\npm\node_modules\nativescript\node_modules\fibers\future.js:566:15)
    at C:\Users\mirko\AppData\Roaming\npm\node_modules\nativescript\lib\common\mobile\mobile-core\android-device-discovery.js:65:49
    at C:\Users\mirko\AppData\Roaming\npm\node_modules\nativescript\lib\common\fiber-bootstrap.js:10:13
    - - - - -
error: could not install *smartsocket* listener: cannot bind to 127.0.0.1:5037: Di norma è consentito un solo utilizzo di ogni indirizzo di socket (protocollo/indirizzo di rete/porta). (10048)
could not read ok from ADB Server
* failed to start daemon *
error: cannot connect to daemon

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
Sending exception report (press Ctrl+C to stop)...
```

What am I doing wrong this time?

**Comment by realtebo** [comment]
I'm trying switching to android native sdk tools instead of using the Genymotion custom version.
I'll update you soon
