### ISSUE TITLE
ValueError: No closing quotation

### ISSUE THREAD

**Issue by georgij** [NativeScript/docs-v7#721]
Python version: 2.7.10 (default, Feb  6 2017, 23:53:20) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
Traceback (most recent call last):
  File "./build-step-metadata-generator.py", line 41, in <module>
    framework_search_paths_parsed = map_and_list((lambda s: "-F" + s), shlex.split(framework_search_paths))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation
Command /bin/sh failed with exit code 1

Whats that? (occur during build)

**Comment by NickIliev** [comment]
Hey, @georgij I think this error log should not be posted in the docs repository. Please post it [here ](https://github.com/NativeScript/NativeScript/issues)or [here](https://github.com/NativeScript/nativescript-cli/issues) and also provide detailed information when and how this is happening (describing the steps needed to reproduce the issue)

**Comment by marcos8896** [comment]
Hi, I was having almost the same problem with my NativeScript projects. My problem was that I had my project folder on Documents/The NativeScript Book's Applications/testapp . After I changed my project directory to something like Documents/NS/testapp and it worked.
My guess is that there was some kind of problem with a long path for my directory folder or maybe because it had an ( ' ) on it.

Hopefully this can help somebody.
